name: Build and Deploy
on: [push]
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install yarn
        run: npm install -g yarn
      - run: yarn
        working-directory: ./example
      - run: yarn export
        working-directory: ./example
      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./example/out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # working-directory: ./example
