name: Sync to Gitee
on:
  push:
jobs:
  sync:
    name: Sync to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:OhYee/next-dynamic-antd-theme.git'
          destination-repo: 'git@gitee.com:OhYee/next-dynamic-antd-theme.git'
